src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"title"},
 * message ="Une autre annonce a deja ce titre")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min =10, max = 100, minMessage = "votre titre doit depassez 10 caractere",
     * maxMessage = "votre titre ne doit pas depasse 100 caractere")
     * 
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=10, max=50, minMessage="Votre introduction doit depasse 20 caractere")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, max=150, minMessage="Votre description doit depasse 20 caractere")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    /**
     * permet de construire le slug de facon automatique
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initialise(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);

        }
    }
    /**
     * permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette formation
     *
     * @return array
     */
    public function getNotAvailabledays()
    {
        $notAvailableDays =[];
        foreach($this->bookings as $booking){
            $resultat =range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 * 
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message = "Attention, la date doit d'arrivée être au bon format !")
     * @Assert\GreaterThan("today",message = "la date doit etre ulterieur a today")
     * 
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message = "Attention, la date de départ doit être au bon format !")
     * @Assert\GreaterThan(propertyPath = "startDate",message = "la date arrive doit etre > a date de depart")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $comment;
    /**
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }
        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }
    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailabledays();

        $bookingDays = $this->getDays();
        // tableau des chaines de caractere de mes joures
        $formatdays = function($day){
            return $day->format('Y-m-d');
        };
        $days = array_map($formatdays,$bookingDays);

        $notAvailable = array_map($formatdays,$notAvailableDays);

        foreach($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }
    /**
     * Permet
     *
     * @return array un tableau
     */
    public function getDays()
    {
        $resultat = range(
            $this->getStartDate()->getTimestamp(),
            $this->getEndDate()->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function($dateTimestamp) {
            return  new \DateTime(date('Y-m-d', $dateTimestamp));
        },$resultat);
        return $days;
    }
    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\dataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $tranformer;
    public function __construct( FrenchToDateTimeTransformer $tranformer)
    {
       $this->transformer = $tranformer; 
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('startDate', TextType::class, $this->getinformation("date d'arrive", "Mettez votre date d'arrive"))
        ->add('endDate', TextType::class, $this->getinformation("date de depart","votre date de depart"))
        ->add('comment', TextareaType::class, $this->getinformation("Vous avez un commentaire","Si vous avez un commentaire n'hesitez pas à le mettre",["required"=> false]));
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use App\Form\ApplicationType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ad/reservez/{slug}", name="book_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

                $booking->setBooker($this->getUser())
                        ->setAd($ad);
                        if(!$booking->isBookableDates()){
                            $this->addFlash(
                                'warning',"les dates que vous avez choisi ne  peuvent pas être reservées elles sont deja prise"
                            );
                        }
                        else{
                            $manager->persist($booking);
                             $manager->flush();
                             return $this->redirectToRoute('booking_show',['id' =>$booking->getId(),
                          'withAlert'=>true
            
                          ]);
                        }
            
                    }
        return $this->render('booking/booking.html.twig', [
            'ad'=>$ad,
            'form'=> $form->createView()
        ]);
    }
    /**
     * Permet de voir une reservate sa route est appele dans redirectToRoute en haut
     *@Route("/booking/{id}", name="booking_show")
     * @param Booking $booking
     * @return Response
     */
    public function booking_show(Booking $booking){
        return $this->render('booking/show.html.twig',[
            'booking'=> $booking
        ]);

    }
}

templates/booking/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation de votre annonce : {{ad.title}}{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
{% endblock %}

{% block body %}
    <div class="container">
        <h2>Reservation de votre annonce : {{ad.title}}</h2>
        <p>Vous êtez entrain de reserver l'annonce de <strong>{{ad.author.fullName}}</strong></p>
        {{form_start(form)}}
            <div class="alert alert-light">
                <h2>Commencer a nous dire vos date</h2>
                <div class="row">
                <div class="col">{{form_row(form.startDate)}}</div>
                <div class="col">{{form_row(form.endDate)}}</div>     
                </div>
            <h2>Montant du sejour <span id="montant">..</span>&euro;</h2>
            <span id="days">0</span> nuit(s) à {{ad.price}}/nuits

            <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{form_row(form.comment)}}
            <h2>Vous avez terminez</h2>
            <p>Vacances de rêve ? Hebergement pour le bulôt ? Peu  importe on est avez vous</p>
            <button class="btn btn-success">Je reservez !!!!</button>
            {{form_end(form)}}
    
          </div>

{% endblock %}
{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
<script>

$(document).ready(function(){
    $('#booking_startDate, #booking_endDate').datepicker({
        format: 'dd/mm/yyyy',
        datesDisabled: [
            {% for day in ad.notAvailabledays %}
                "{{ day.format('d/m/Y') }}",
            {% endfor %}
        ],
        startDate : new Date()
    });
    $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
});
function calculateAmount(){
    //on choper les date
    const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
    
    const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
    if(startDate && endDate && startDate < endDate){
        const DAY_TIME = 24 * 60 *60 * 1000;
       const interval = endDate.getTime()-startDate.getTime();
       const days = interval / DAY_TIME;
       const amount = days * {{ ad.price }};
       $('#days').text(days);
       $('#montant').text(amount.toLocaleString('fr-FR'));

    }
}
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}
{% block title %}Votre reservation{% endblock %}
{% block body %}
{% set ad = booking.ad %}
{% set author = booking.ad.author %}
    <div class="container">
        <h1>votre reservation numero : {{ booking.id }} </h1>
         {% if app.request.query.get('withAlert')%}
           <div class="alert alert-success">
               <h4 class="alert-heading"> Bravo !</h4>
               <p> Votre reservation auprès de 
                <strong> 
                    <a href="{{ path('user_show', {'slug': author.slug }) }}">{{author.fullName}}</a>
                </strong> pour l'annonces 
                <strong>
                        <a href="{{ path('voir_annonce', { 'slug': ad.slug}) }}"> {{ad.title }}</a>
                </strong>
                a bien été prise en compte
            </p>
           </div>
         {% endif %}
        <div class="row">
                <div class="col">
                
                    <div class="alert alert-light">
                        <h2>Details</h2>
                        <dl class="row">
                        <dt class="col-md-4">Numero</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrive</dt>
                        <dd class="col-md-8">{{booking.startDate |date('d/m/y') }}</dd>
                        <dt class="col-md-4">Date de depart</dt>
                        <dd class="col-md-8">{{booking.endDate |date('d/m/y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant</dt>
                        <dd class="col-md-8">{{booking.amount}}</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment}}</dd>
                        </dl>
                        <h2 class="alert-heading">Vôtre hote</h2>
                        <div class="row mb-3">
                            <div class="col-3">
                                <img src="{{ author.picture}}" class="avatar avatar-medium" alt="{{ author.fullName}}">
                            </div>
                            <div class="col-9">
                                <h4>
                                    <a href="{{ path('user_show', {'slug': author.slug }) }}">{{author.fullName}}</a>
                                </h4>
                                <span class="badge badge-primary">{{ author.ads|length }} annonces</span>
                            </div>
                        </div>
                        
                        {{ author.description | raw }}
                        <a href="{{ path('user_show', {'slug': author.slug }) }}" class="btn btn-primary"> plus d'info {{ author.firstName }}</a>
                    </div>
                </div>
                <div class="col">
                    <div class="alert light">
                        <h2 class="alert-heading">Votre hébergement</h2>
                        <h4> 
                            <a href=" {{ path('voir_annonce', { 'slug': ad.slug}) }}">{{ ad.title }}</a>
                        </h4>
                        <img src="{{ ad.coverImage}}" alt="{{ ad.title}}" class="img-fluid">
                        {{ ad.content | raw}}
                        <a href="{{ path('voir_annonce', { 'slug': ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                    </div>
                </div>
        </div>
    </div>

{% endblock %}